ALTER TABLE ONLY public.cars DROP CONSTRAINT IF EXISTS cars_people_fk;
ALTER TABLE public.cars ALTER COLUMN id DROP DEFAULT;

DROP TABLE IF EXISTS public.cars CASCADE;
DROP TABLE IF EXISTS public.people CASCADE;
